# Set the base image
FROM php:8.2-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    curl \
    unzip \
    git \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libpq-dev \
    supervisor && \
    docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    zip && \
    pecl install redis && \
    docker-php-ext-enable redis

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Remove default server definition
RUN rm -rf /var/www/html

# Copy supervisor config
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Copy application source code and set permissions
COPY . /var/www
RUN chown -R www-data:www-data /var/www

# Create necessary directories and set permissions
RUN mkdir -p /var/log/supervisor /var/run
RUN chown -R www-data:www-data /var/log/supervisor /var/run

# Expose the PHP-FPM port
EXPOSE 9000

# Switch to root user for the CMD
USER root

# Set the CMD to run supervisor
# CMD ["supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]